### ISSUE TITLE
搭完服务器后,报了code 1002

### ISSUE THREAD

**Issue by 15766736837** [taxiao213/Webrtc_Android#1]
已经部署了自己的服务器了
错误信息
onClose == code 1002 reason == Invalid status code received: 200 Status line: HTTP/1.1 200  remote == false

**Comment by 15766736837** [comment]
onClose == code 1002 reason == Invalid status code received: 302 Status line: HTTP/1.1 302  remote == false

**Comment by taxiao213** [comment]
已连线解决
